package com.example.onlineStore.controller;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import com.example.onlineStore.models.User;
import com.example.onlineStore.Repositories.UserRepository;
import java.util.List;
import java.util.ArrayList;

@RestController // This means that this class is a Controller
public class UserController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @RequestMapping(value="/addadmin", method=RequestMethod.POST)
    public boolean addAdmin(@RequestBody User user)
	    {
       user.setType("admin");
        if(userRepository.save(user) != null)
            return true;
        return false;
      }
    @RequestMapping(value="/addbuyer", method=RequestMethod.POST)
    public boolean addBuyer(@RequestBody User user)
    {
        user.setType("buyer");
        if(userRepository.save(user) != null)
            return true;
        return false;
    }
    @RequestMapping(value="/addstoreowner", method=RequestMethod.POST)
    public boolean addStoreOwner(@RequestBody User user)
    {
        user.setType("store_owner");
        if(userRepository.save(user) != null)
            return true;
        return false;
    }

    @RequestMapping(value="/all", method=RequestMethod.GET)
     public List<User> getAllUsers() {
  		  //TODO Auto-generated method stub
    		Iterable<User> usersIter= userRepository.findAll();
    		List<User> all= new ArrayList<User>();
    		for(User user: usersIter)
    			all.add(user);

    		return all;
	   }
}
