package com.example.onlineStore.controller;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import com.example.onlineStore.models.User;
import com.example.onlineStore.services.IUserServices;
import java.util.List;

@RestController // This means that this class is a Controller
public class UserController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private IUserServices srv;

    @RequestMapping(value="/adminRegister", method=RequestMethod.POST)
    public boolean registerAsAdmin(@RequestBody User user)
    {
		user.setType("admin");
		return srv.addUser(user);
    }
    @RequestMapping(value="/buyerRegister", method=RequestMethod.POST)
    public boolean registerAsBuyer(@RequestBody User user)
    {
        user.setType("buyer");
        return srv.addUser(user);
    }
    @RequestMapping(value="/ownerRegister", method=RequestMethod.POST)
    public boolean registerAsStoreOwner(@RequestBody User user)
    {
        user.setType("store_owner");
        return srv.addUser(user);
    }
    
    @RequestMapping(value="/login", method=RequestMethod.POST)
    public boolean login(@RequestParam String username, @RequestParam String pass)
    {
		return srv.verifyLogin(username,pass);
    }
    
    @RequestMapping(value="/allUsers", method=RequestMethod.GET)
     public List<User> getAllUsers() 
    {
    	return srv.getAll();
    }

    @RequestMapping(value="/logout", method=RequestMethod.GET)
    public void logout()
    {
        srv.logout();
    }
}
